apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: { { .Values.namespace } }
type: Opaque
data:
  POSTGRES_HOST: { { .Values.postgresHost | b64enc } }
  POSTGRES_DB: { { .Values.postgresKeycloakDB | b64enc } }
  POSTGRES_USER: { { .Values.postgresUser | b64enc } }
  POSTGRES_PASSWORD: { { .Values.postgresPassword | b64enc } }
  POSTGRES_PORT: { { .Values.postgresPort | b64enc } }
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: { { .Values.namespace } }
type: Opaque
data:
  KEYCLOAK_ADMIN: { { .Values.keycloakAdmin | b64enc } }
  KEYCLOAK_ADMIN_PASSWORD: { { .Values.namespace | b64enc } }
---
apiVersion: v1
kind: Secret
metadata:
  name: artifact-registry-secret
  namespace: { { .Values.namespace } }
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_GAR_CREDENTIALS>
---

